### ISSUE TITLE
Consider replacing `JsonRpcProvider` with `Provider`

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat-ignition#48]
The codebase uses [`JsonRpcProvider`](https://docs.ethers.io/v5/single-page/#/v5/api/providers/jsonrpc-provider/) everywhere, but that seems like an unnecessary constraint. In ethers, that type implies an HTTP connection, but that's not always the case (for example, in the in-memory Hardhat provider). We should consider using the plain `Provider` type instead.

**Comment by alcuadrado** [comment]
I think this is needed, as the `JsonRpcProvider` is the only one that can give you access to the signers.

We use also use `JsonRpcProvider` within `hardhat-ethers`.

Maybe an alternative is to have some kind of `ProviderWithSigners` class/interface?
