### ISSUE TITLE
Remove `logging` parameter in Ignition's methods

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat-ignition#60]
`IgnitionCore.deploy` and `IgnitionCore.diff` accept an optional `logging` parameter that overrides the configuration passed in the constructor. But its current behavior can be incorrect (see [comment](https://github.com/nomiclabs/hardhat-ignition/pull/42#discussion_r669867577)) and its intended usage is not clear.

We should remove it, both in `IgnitionCore` and in the plugin's `HardhatIgnition` class.

**Comment by alcuadrado** [comment]
Just a comment without a lot of context: we do need a way to deploy contracts without output. It would, for example, be used for running smart contract tests.

**Comment by fvictorio** [comment]
Agree. As far as I understand, right now that is handled at the constructor level by setting the `test` option to `true`. But it would probably make sense to be able to decide that at the method call level. Anyway, I'm pretty sure that that will surface when we iterate over the way unit tests are written in the sample projects.
